import { createClient, createServiceClient, type RlsClient } from "@/lib/supabase/server";
import { buildWorkspaceReport } from "@/lib/report";
import { getLlm, isLlmConfigured } from "@/lib/extraction/llm";
import { workspaceBusinessIds, type WorkspaceRow } from "@/lib/workspace";

/**
 * The at-a-glance "weekly briefing" for the Home command center — a plain-English
 * headline + 2–3 sentences that tell a busy, non-technical owner the story of
 * their market (standing vs rivals, the biggest change, the one thing to do).
 * Generated by Claude over the workspace's own data and cached on the workspace
 * (settings.briefing) so Home stays fast and cheap.
 */

export interface BriefingLink {
  name: string;   // the competitor
  url: string;    // where a client would book them (or their site)
  kind: "booking" | "website";
}

export interface Briefing {
  headline: string;
  summary: string;
  /** Competitors' real booking/website links (from our data, never invented by
   *  the model) so the owner can go straight to a rival's booking page. */
  links?: BriefingLink[];
  at: string;
}

// Known online-booking platforms med spas / salons use — a link on one of these
// hosts is a real "book now" page, worth surfacing over the plain website.
const BOOKING_HOST =
  /vagaro|boulevard|blvd\.co|glossgenius|mindbody|squareup|square\.site|acuityscheduling|squarespace-scheduling|setmore|gettimely|timelyapp|zenoti|aestheticrecord|withcherry|gocherry|booksy|phorest|fresha|calendly|schedulicity|janeapp/i;

/** Pick each competitor's best "go book them" link from our stored identities +
 *  website. Deterministic — no LLM, so links are always real. Competitors that
 *  appear in a recent change are prioritized (that's who the briefing calls out). */
async function competitorLinks(ws: WorkspaceRow, priorityNames: string[]): Promise<BriefingLink[]> {
  const svc = createServiceClient();
  const ids = await workspaceBusinessIds(ws, svc);
  const compIds = ids.all.filter((id) => id !== ids.targetId);
  if (!compIds.length) return [];
  const [{ data: bizRows }, { data: idents }] = await Promise.all([
    svc.from("business").select("id,canonical_name,website").in("id", compIds),
    svc.from("external_identity").select("business_id,platform,url").in("business_id", compIds),
  ]);
  const identsByBiz = new Map<string, { platform: string; url: string }[]>();
  for (const r of idents ?? []) {
    const arr = identsByBiz.get(r.business_id as string) ?? [];
    arr.push({ platform: r.platform as string, url: r.url as string });
    identsByBiz.set(r.business_id as string, arr);
  }
  const links: BriefingLink[] = [];
  for (const b of bizRows ?? []) {
    const rows = identsByBiz.get(b.id as string) ?? [];
    const booking = rows.find((r) => r.url && BOOKING_HOST.test(r.url));
    const url = booking?.url ?? (b.website as string | undefined);
    if (!url) continue;
    links.push({ name: b.canonical_name as string, url, kind: booking ? "booking" : "website" });
  }
  // rank: mentioned-in-a-change first, then booking links, then the rest
  const pri = new Set(priorityNames.map((n) => n.toLowerCase()));
  links.sort((a, b) => {
    const ap = pri.has(a.name.toLowerCase()) ? 0 : 1;
    const bp = pri.has(b.name.toLowerCase()) ? 0 : 1;
    if (ap !== bp) return ap - bp;
    const ab = a.kind === "booking" ? 0 : 1;
    const bb = b.kind === "booking" ? 0 : 1;
    return ab - bb;
  });
  return links.slice(0, 4);
}

const SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    headline: { type: "string", description: "≤10 words, punchy, plain English — the single most important takeaway." },
    summary: { type: "string", description: "2–3 short sentences: how they're doing vs rivals, the biggest recent change, and the top move. Real names/numbers, no jargon." },
  },
  required: ["headline", "summary"],
};

const SYSTEM =
  "You are Ask Rani, briefing a busy, non-technical local-business owner. Write ONLY from the DATA. Be concrete (business names, numbers), warm, and plain — no jargon, no hedging. The owner is \"you\".";

// Cut any string at the first tool-call/XML artifact (e.g. "…deals.</summary> </invoke>")
// that models occasionally bleed into a field, then trim.
function strip(s?: string): string {
  const v = String(s ?? "");
  const i = v.search(/<\/|<(parameter|function|antml|invoke|summary|headline)\b/i);
  return (i >= 0 ? v.slice(0, i) : v).replace(/\s+/g, " ").trim();
}

export async function generateBriefing(ws: WorkspaceRow, db?: RlsClient): Promise<Briefing> {
  const at = new Date().toISOString();
  if (!isLlmConfigured()) {
    return { headline: "Your market at a glance", summary: "Connect an AI key to get a written weekly briefing.", at };
  }
  const r = await buildWorkspaceReport(ws, 30, db);
  const changedNames = r.events.slice(0, 10).map((e) => e.business).filter(Boolean) as string[];
  const links = await competitorLinks(ws, changedNames);
  const context = {
    you: r.pricing.find((p) => p.isTarget)?.name ?? ws.name,
    standing: {
      reputation: r.reputation.map((x) => ({ name: x.name, you: x.isTarget, rating: x.rating, reviews: x.reviewCount })),
      pricing: r.pricing.map((p) => ({ name: p.name, you: p.isTarget, avgPrice: p.avgPrice, items: p.offers })),
      businessesWatched: r.snapshot.monitoredBusinesses,
    },
    recentChanges: r.events.slice(0, 10).map((e) => ({ business: e.business, type: e.type, summary: e.summary })),
    topActions: r.recommendations.slice(0, 3).map((x) => ({ title: x.title, action: x.action })),
  };
  try {
    const { data } = await getLlm().callStructured<{ headline: string; summary: string }>({
      system: SYSTEM,
      text: `Write the weekly briefing.\n\nDATA (JSON):\n${JSON.stringify(context)}`,
      schema: SCHEMA,
      tier: "extract",
      maxTokens: 350,
    });
    return { headline: strip(data.headline) || "Your market at a glance", summary: strip(data.summary), links, at };
  } catch {
    return { headline: "Your market at a glance", summary: "We're still gathering enough to summarize — check back after the next scan.", links, at };
  }
}

/** Cached briefing, regenerated when older than maxAgeHours. */
export async function getOrMakeBriefing(ws: WorkspaceRow, maxAgeHours = 12): Promise<Briefing> {
  const supabase = await createClient();
  const { data } = await supabase.from("workspace").select("goals").eq("id", ws.id).maybeSingle();
  const cached = (data?.goals as any)?.briefing as Briefing | undefined;
  if (cached?.at && Date.now() - new Date(cached.at).getTime() < maxAgeHours * 3600_000 && cached.summary) {
    // sanitize on read so any previously-cached artifact is cleaned in place
    return { ...cached, headline: strip(cached.headline), summary: strip(cached.summary) };
  }
  const fresh = await generateBriefing(ws);
  // persist with the service client (workspace.goals isn't member-writable via RLS).
  // Cache lives under goals.briefing (workspace has no dedicated settings column).
  const svc = createServiceClient();
  const { data: cur } = await svc.from("workspace").select("goals").eq("id", ws.id).maybeSingle();
  await svc
    .from("workspace")
    .update({ goals: { ...((cur?.goals as any) ?? {}), briefing: fresh } })
    .eq("id", ws.id);
  return fresh;
}
