import { createClient, createServiceClient } from "@/lib/supabase/server";
import { buildWorkspaceReport } from "@/lib/report";
import { getLlm, isLlmConfigured } from "@/lib/extraction/llm";
import type { WorkspaceRow } from "@/lib/workspace";

/**
 * The at-a-glance "weekly briefing" for the Home command center — a plain-English
 * headline + 2–3 sentences that tell a busy, non-technical owner the story of
 * their market (standing vs rivals, the biggest change, the one thing to do).
 * Generated by Claude over the workspace's own data and cached on the workspace
 * (settings.briefing) so Home stays fast and cheap.
 */

export interface Briefing {
  headline: string;
  summary: string;
  at: string;
}

const SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    headline: { type: "string", description: "≤10 words, punchy, plain English — the single most important takeaway." },
    summary: { type: "string", description: "2–3 short sentences: how they're doing vs rivals, the biggest recent change, and the top move. Real names/numbers, no jargon." },
  },
  required: ["headline", "summary"],
};

const SYSTEM =
  "You are Ask Rani, briefing a busy, non-technical local-business owner. Write ONLY from the DATA. Be concrete (business names, numbers), warm, and plain — no jargon, no hedging. The owner is \"you\".";

// Cut any string at the first tool-call/XML artifact (e.g. "…deals.</summary> </invoke>")
// that models occasionally bleed into a field, then trim.
function strip(s?: string): string {
  const v = String(s ?? "");
  const i = v.search(/<\/|<(parameter|function|antml|invoke|summary|headline)\b/i);
  return (i >= 0 ? v.slice(0, i) : v).replace(/\s+/g, " ").trim();
}

export async function generateBriefing(ws: WorkspaceRow): Promise<Briefing> {
  const at = new Date().toISOString();
  if (!isLlmConfigured()) {
    return { headline: "Your market at a glance", summary: "Connect an AI key to get a written weekly briefing.", at };
  }
  const r = await buildWorkspaceReport(ws);
  const context = {
    you: r.pricing.find((p) => p.isTarget)?.name ?? ws.name,
    standing: {
      reputation: r.reputation.map((x) => ({ name: x.name, you: x.isTarget, rating: x.rating, reviews: x.reviewCount })),
      pricing: r.pricing.map((p) => ({ name: p.name, you: p.isTarget, avgPrice: p.avgPrice, items: p.offers })),
      businessesWatched: r.snapshot.monitoredBusinesses,
    },
    recentChanges: r.events.slice(0, 10).map((e) => ({ business: e.business, type: e.type, summary: e.summary })),
    topActions: r.recommendations.slice(0, 3).map((x) => ({ title: x.title, action: x.action })),
  };
  try {
    const { data } = await getLlm().callStructured<{ headline: string; summary: string }>({
      system: SYSTEM,
      text: `Write the weekly briefing.\n\nDATA (JSON):\n${JSON.stringify(context)}`,
      schema: SCHEMA,
      tier: "extract",
      maxTokens: 350,
    });
    return { headline: strip(data.headline) || "Your market at a glance", summary: strip(data.summary), at };
  } catch {
    return { headline: "Your market at a glance", summary: "We're still gathering enough to summarize — check back after the next scan.", at };
  }
}

/** Cached briefing, regenerated when older than maxAgeHours. */
export async function getOrMakeBriefing(ws: WorkspaceRow, maxAgeHours = 12): Promise<Briefing> {
  const supabase = await createClient();
  const { data } = await supabase.from("workspace").select("goals").eq("id", ws.id).maybeSingle();
  const cached = (data?.goals as any)?.briefing as Briefing | undefined;
  if (cached?.at && Date.now() - new Date(cached.at).getTime() < maxAgeHours * 3600_000 && cached.summary) {
    // sanitize on read so any previously-cached artifact is cleaned in place
    return { ...cached, headline: strip(cached.headline), summary: strip(cached.summary) };
  }
  const fresh = await generateBriefing(ws);
  // persist with the service client (workspace.goals isn't member-writable via RLS).
  // Cache lives under goals.briefing (workspace has no dedicated settings column).
  const svc = createServiceClient();
  const { data: cur } = await svc.from("workspace").select("goals").eq("id", ws.id).maybeSingle();
  await svc
    .from("workspace")
    .update({ goals: { ...((cur?.goals as any) ?? {}), briefing: fresh } })
    .eq("id", ws.id);
  return fresh;
}
